[package]
name = "obsiditero"
version = "0.1.0"
edition = "2024"
description = "Obsidian interaction with Zotero API"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.49"
sqlite-wasm-rs = { version = "0.3", default-features = false, features = ["precompiled"] }